### PR TITLE
Created Dutch translation

### PR DESCRIPTION
**Pull request by NaamloosDT**

### CODE REVIEW

**Comment by Gatobrujo** [comment]
El feb. 16, 2017 5:17 PM, "Naamloos" <notifications@github.com> escribió:

------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/nagadomi/waifu2x/pull/173
Commit Summary

   - Updated Dutch translation

File Changes

   - *A* webgen/locales/nl.yml
   <https://github.com/nagadomi/waifu2x/pull/173/files#diff-0> (30)

Patch Links:

   - https://github.com/nagadomi/waifu2x/pull/173.patch
   - https://github.com/nagadomi/waifu2x/pull/173.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nagadomi/waifu2x/pull/173>, or mute the thread

**Comment by nagadomi** [comment]
Thanks!
It may take some time to update website.

**Comment by NaamloosDT** [comment]
No problem =)

**Comment by NaamloosDT** [comment]
By the way, @nagadomi the dutch name for our language is "Nederlands"

**Comment by nagadomi** [comment]
Sorry. Fixed https://github.com/nagadomi/waifu2x/commit/81a4de1fa3ed2addcf670aea6a2512c100241c35

**Comment by nagadomi** [comment]
language detection is not working yet.

**Comment by NaamloosDT** [comment]
Ah, is okay. Thanks for updating :) If you ever need new translations, let me know

**Comment by nagadomi** [comment]
Thanks

**Pull request merged**
