### PR TITLE
Web Application Improvement (text and design)

### PR DESCRIPTION
**Pull request by vitaliylag**
Here's these improvements:
1. Adding warning about using high level of noise reduction
2. Adding Russian language (I'm native Russian speaker)
3. Many little design improvements

About noise reduction: People don't know what variant is better, but noise reduction makes image look badly if image didn't have noise before. Many people use noise reduction when it doesn't need because they don't know that it's not good idea to use denoise every time. People are disappointed in the algorithm but it's unfairly because algorithm is very good.

### CODE REVIEW

**Comment by nagadomi** [comment]
That help-message cannot be accepted even if that was true.
>High (not recommended)
>Warning! You should use noise reduction only if image really has noise because in other way it makes image looks worse. Additionally we never recommend to use high level of noise reduction, it almost always makes image worse, it makes sense for only some rare cases when image had really bad quality from the beginning.

Can you change the help-message something like this?
>When using 2x scaling, we never recommend to use high level of noise reduction, it almost always makes image worse, it makes sense for only some rare cases when image had really bad quality from the beginning.

**Comment by vitaliylag** [comment]
Done. But what was wrong in previous help-message? May be there's need less frightening message? Somethink like that:
When using 2x scaling, you should use noise reduction if image really has noise or it may cause opposite effect. Also it's not recommend to use high level of noise reduction, if image had not really bad quality from the beginning then high level almost always makes image worse.

PS. Sorry for my English

**Comment by nagadomi** [comment]
Thanks.
In japan, popular card game uses very noisy JPEG image. (high)noise reduction(without 2x scaling) is basic usage for that.

**Comment by vitaliylag** [comment]
Well, I do say noise reduction is very great feature, it's really amazing, but what I want to say is that each program, algorithm and feature need to use smart. In some case I can get really amazing result that I can not get with any other algorithm, in some case I should use NNEDI3 (some video), in some case I don't need noise reduction.

«In japan, popular card game uses very noisy JPEG image» — I have tested noise reduction on random anime art in my collection. In 70% cases better choice is medium noise reduction, in that cases noise reduction is really great future. In 25% cases better choice is no noise reduction (just upscaling, if I choose medium noise reduction then I get worse image than without noise reduction). In 5% cases better choice is high noise reduction. In other words I think people should know that they must use algorithm wisely.

By the way. I have tested 2x scale on anime Tokyo ESP. I take 1080p (BD), downscaled it to 540p and upscaled it to 1080p with the waifu2x. And I get 2 times better quality than was before! That mean anime creators have used worse upscale than waifu2x can do! And if anime creation would use waifu2x in the future then anime can get better quality without any costs. It's really amazing, thanks =)

**Pull request merged**
